<?php 
namespace LeviZwannah\PesapalSdk;

use Exception;
use GuzzleHttp\Client;
use LeviZwannah\PesapalSdk\Traits\AssertTrait;
use LeviZwannah\PesapalSdk\Traits\PropertyTrait;

/**
 * After making any request, use the `response()` method to
 * get the response object from the request.
 * @package levizwannah\pesapal-sdk-php
 */
class Pesapal{

    /*------------------------------
    | Constants
    |-------------------------------
    */
    /**
     * Payment Status Code
     */
    const INVALID = 0;

    /**
     * Payment Status Code
     */
    const COMPLETED = 1;

    /**
     * Payment Status Code
     */
    const FAILED = 2;

    /**
     * Payment Status Code
     */
    const REVERSED = 3;

    /*-----------------------------------
    | Traits
    |------------------------------------
    */
    use PropertyTrait;
    use AssertTrait;

    /**
     * The base url
     * @var string
     */
    public $baseUrl = "https://pay.pesapal.com/v3";

    /**
     * The environment
     * @var string
     */
    public $env = "live";

    /**
     * Consumer Key Defaults to Kenyan Merchant sandbox
     * Consumer key
     * @var string
     */
    public $key = "qkio1BGGYAXTu2JOfm7XSXNruoZsrqEW";

    /**
     * Consumer Secret - Defaults to Kenyan Merchant Sandbox
     * Consumer secret
     * @var string
     */
    public $secret = "osGQ364R49cXKeOYSpaOnT++rHs=";

    /**
     * The current response for the recent request.
     * @var object|null
     */
    public $response = null;

    public function __construct(array $config)
    {
        $this->configure($config);
        
        if($this->env != "live"){
            $this->baseUrl = "https://cybqa.pesapal.com/pesapalv3";
        }
    }

    /**
     * Creates a new Pesapal object
     * @param array $config The config array should have the keys that
     * exists in the pesapal object.
     * 
     * @return Pesapal
     */
    public static function new(array $config){
        return new static($config);
    }

    /**
     * Maps the key => values of the config to this object's properties
     * @param array $config
     * 
     */
    public function configure(array $config){

        foreach($config as $key => $val){
            $this->$key = $val;
        }

        return $this;
    }

    /**
     * Returns the error object
     * @return object
     */
    public function error(){

        return $this->response()->error;
    }

    /**
     * Checks if the request returned a successful result
     * @return bool
     */
    public function accepted(){

        $this->assertProperty("response");

        return empty($this->response()->error) 
                && $this->response()->status == 200;
    }

    /**
     * Gets the HTTP object
     * @return Client
     */
    public function http(){

        return new Client([
            'Accept' => 'application/json',
            'Content-Type' => 'application/json'
        ]);
    }

    /**
     * Gets the access token
     * @return string
     */
    public function token(){

        $this->request([
            'consumer_key' => $this->key,
            'consumer_secret' => $this->secret
        ], 
        "/api/Auth/RequestToken", false);

        return $this->response()->token;
    }

    /**
     * Registers the IPN URL for your application and returns the IPN ID
     * @param string $ipnUrl
     * @param string $httpMethod
     * 
     * @return Pesapal
     */
    public function registerIpn($ipnUrl, $httpMethod = "POST"){

        $this->request([
            "url" => $ipnUrl,
            "ipn_notification_type" => $httpMethod
        ], "/api/URLSetup/RegisterIPN");

        return $this;
    }

    /**
     * Gets registered IPNs
     * @return Pesapal
     */
    public function ipns(){

        $this->request([], "/api/URLSetup/GetIpnList", true, 'get');
        return $this;
    }

    /**
     * @param OrderData $order
     * Submit order request
     * @return Pesapal
     */
    public function order($order){

        $this->request($order->data(), "/api/Transactions/SubmitOrderRequest");
        return $this;
    }
    
    /**
     * Gets a transaction status.
     * or Gets the status of a payment.
     * @param string $trackingId Unique order id generated by Pesapal 
     * e.g 7e6b62d9-883e-440f-a63e-e1105bbfadc3. Attached as a query parameter 
     * to the getTransactionStatus endpoint to get status of your submitted order.
     * 
     * @return Pesapal
     */
    public function status($trackingId){

        $this->request([], "/api/Transactions/GetTransactionStatus?orderTrackingId=$trackingId", true, "get");
        return $this;
    }

    /**
     * Makes a request and ensure it is accepted before returning
     * the response.
     * @param array $data
     * @param string $endpoint
     * @param bool $authenticated adds token to the request
     * @param string $method http method (lowercase)
     * 
     * @return object response
     */
    public function request($data, $endpoint, $authenticated = true, $method = "post"){
        
        $http = $this->http();
        $endpoint = $this->baseUrl . ($endpoint);
        if(!$authenticated){
            $response = $http->$method($endpoint, [
                'json' => $data
            ]);
        }
        else{
            $response = $http->$method($endpoint, [
                'json' => $data,
                'headers' => [
                    'Authorization' => 'Bearer '. $this->token()
                ]
            ]);
        }
        
        $this->response(json_decode($response->getBody()));

        return $this->response();
    }

    /**
     * Used in the IPN handler script to tell pesapal that the 
     * notification was received successfully.
     * @param int $status - status code (200 - success, 500 - error)
     * @return Pesapal
     */
    public function received($status = 200){

        header("Content-Type: application/json");

        echo json_encode([
            "status" => $status,
            "description" => "Received"
        ]);

        return $this;
    }
}

?>